#!/bin/bash
# ...
# kasutajate lisamise failist skript
if [ $# -ne 1 ]; then
	echo "Kasutusjuhend: $0 failinimi"
else
	failinimi=$1

if [ -f $failinimi -a -r $failinimi ]; then
	echo "Fail on korras"
	for nimi in $(cat $failinimi)
	do
	sh lisa_kasutaja $nimi # lisa_kasutaja skript käivitub sellega
	done
else
echo "Probleem failiga $failinimi"
fi
# Parameetrite kontrolli lõpp
fi
